import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('home page builds the full static page from semantic blocks and shared progress bars', async () => {
    const [page, styles] = await Promise.all([
        readFile('src/pages/main/home/HomePage.tsx', 'utf8'),
        readFile('src/pages/main/home/HomePage.scss', 'utf8'),
    ])

    assert.match(page, /import \{ ProgressBar \} from '@\/components\/ProgressBar'/)
    assert.match(page, /import \{ ContractLoading \} from '@\/components\/ContractLoading'/)
    assert.match(page, /import \{ ConfirmPopup \} from '@\/components\/ConfirmPopup'/)
    assert.match(page, /import \{ Icon \} from '@\/components\/Icon'/)
    assert.match(page, /import \{ message \} from '@\/components\/Message'/)
    assert.match(page, /import \{ InfiniteScroll \} from '@\/components\/InfiniteScroll'/)
    assert.match(page, /import \{ Popup \} from '@\/components\/Popup'/)
    assert.match(page, /import \{ SegmentedTabs \} from '@\/components\/SegmentedTabs'/)
    assert.match(page, /import \{[\s\S]*useCallback,[\s\S]*useEffect,[\s\S]*useRef,[\s\S]*useState,[\s\S]*\} from 'react'/)
    assert.match(page, /import \{ useTranslation \} from 'react-i18next'/)
    assert.match(page, /import \{[\s\S]*isAddress,[\s\S]*type Address,[\s\S]*\} from 'viem'/)
    assert.match(page, /import \{ PROJECT_TOKEN \} from '@\/config'/)
    assert.match(page, /import \{ ROUTE_PATH, useAppNavigate \} from '@\/router'/)
    assert.match(page, /import \{[\s\S]*addDecimalNumbers,[\s\S]*divideDecimalNumbers,[\s\S]*\} from '@\/shared\/calculations\/decimalNumbers\.ts'/)
    assert.match(page, /import \{ getOrders \} from '@\/features\/order\/api\.ts'/)
    assert.match(page, /import type \{[\s\S]*Order as ApiOrder,[\s\S]*OrderListParams,[\s\S]*\} from '@\/features\/order\/types\.ts'/)
    assert.match(page, /formatAmount/)
    assert.match(page, /formatDappAmountUnits/)
    assert.match(page, /waitForDappContractDataSync/)
    assert.match(page, /parseHomeDepositAmount/)
    assert.match(page, /submitHomeDepositOrder/)
    assert.match(page, /readErc20Balance/)
    assert.match(page, /getUsdtAddress/)
    assert.match(page, /readAigoProjectPendingDynamicReward/)
    assert.match(page, /readAigoProjectPendingStaticRewards/)
    assert.match(page, /readAigoProjectMinDepositUsdt/)
    assert.match(page, /readAigoProjectMaxDepositUsdt/)
    assert.match(page, /readAigoProjectOrder/)
    assert.match(page, /writeAigoProjectClaimStaticRewards/)
    assert.match(page, /getReferralCode/)
    assert.match(page, /useDappStore/)
    assert.match(page, /useUserStore/)
    assert.match(page, /const \{ pushRoute \} = useAppNavigate\(\)/)
    assert.match(page, /incomeIcon from '@\/assets\/home\/income\.png'/)
    assert.match(page, /usdtIcon from '@\/assets\/common\/usdt\.png'/)
    assert.match(page, /type HomeOrderStatus = 'active' \| 'completed'/)
    assert.match(page, /HOME_ORDER_STATUS_LIST/)
    assert.match(page, /HOME_ORDER_PAGE_SIZE/)
    assert.match(page, /HOME_SCREEN_REFRESH_INTERVAL_MS = 10_000/)
    assert.match(page, /HOME_ORDER_API_STATUS/)
    assert.match(page, /active:\s*1/)
    assert.match(page, /completed:\s*0/)
    assert.match(page, /mapApiOrderToHomeOrder/)
    assert.match(page, /progressMultipleText:\s*string/)
    assert.match(page, /claimableLoading:\s*boolean/)
    assert.match(page, /progressLoading:\s*boolean/)
    assert.match(page, /dateText:\s*order\.created_at/)
    assert.match(page, /const status = order\.status === HOME_ORDER_API_STATUS\.active \? 'active' : 'completed'/)
    assert.match(page, /const progressCurrentValue = status === 'completed' \? order\.total_amount : '0'/)
    assert.match(page, /progressCurrentValue,/)
    assert.match(page, /progressCurrentText:\s*formatAmount\(progressCurrentValue\)/)
    assert.match(page, /progressLoading:\s*status !== 'completed'/)
    assert.doesNotMatch(page, /progressCurrentValue:\s*order\.release_amount/)
    assert.doesNotMatch(page, /progressCurrentText:\s*formatAmount\(order\.release_amount\)/)
    assert.match(page, /progressMultipleText:\s*divideDecimalNumbers\(order\.total_amount, order\.amount, 2\)/)
    assert.doesNotMatch(page, /formatHomeOrderDate/)
    assert.match(page, /createHomeOrderListParams/)
    assert.match(page, /status:\s*HOME_ORDER_API_STATUS\[status\]/)
    assert.match(page, /status === 'completed'/)
    assert.match(page, /page_no:\s*pageNo/)
    assert.match(page, /page_size:\s*HOME_ORDER_PAGE_SIZE/)
    assert.match(page, /const \[activeOrderStatus, setActiveOrderStatus\] = useState<HomeOrderStatus>\('active'\)/)
    assert.match(page, /const \[homeOrderPageNo, setHomeOrderPageNo\] = useState\(1\)/)
    assert.match(page, /const \[homeOrders, setHomeOrders\] = useState<HomeOrder\[\]>\(\[\]\)/)
    assert.match(page, /const \[homeOrderLoading, setHomeOrderLoading\] = useState\(false\)/)
    assert.match(page, /const \[homeOrderHasNextPage, setHomeOrderHasNextPage\] = useState\(false\)/)
    assert.match(page, /const \[homeScreenRefreshVersion, setHomeScreenRefreshVersion\] = useState\(0\)/)
    assert.match(page, /const homeScreenRefreshTimerRef = useRef<number \| undefined>\(undefined\)/)
    assert.doesNotMatch(page, /homeOrderRefreshVersion/)
    assert.doesNotMatch(page, /usdtBalanceRefreshVersion/)
    assert.match(page, /const \[homeQuotaProgress, setHomeQuotaProgress\] = useState\(\{[\s\S]*amount:\s*'0',[\s\S]*totalAmount:\s*'0',[\s\S]*loading:\s*true,[\s\S]*\}\)/)
    assert.match(page, /const \[homeDepositMinimum, setHomeDepositMinimum\] = useState\(0n\)/)
    assert.match(page, /const \[homeDepositMaximum, setHomeDepositMaximum\] = useState\(0n\)/)
    assert.match(page, /const \[homeDepositLimitsLoaded, setHomeDepositLimitsLoaded\] = useState\(false\)/)
    assert.match(page, /const \[staticRewardTokenAmount, setStaticRewardTokenAmount\] = useState\(0n\)/)
    assert.match(page, /const \[staticRewardTokenLoading, setStaticRewardTokenLoading\] = useState\(true\)/)
    assert.match(page, /const \[staticRewardOrderIndexes, setStaticRewardOrderIndexes\] = useState<bigint\[\]>\(\[\]\)/)
    assert.match(page, /const \[showStaticRewardClaimPopup, setShowStaticRewardClaimPopup\] = useState\(false\)/)
    assert.match(page, /const \[homeDepositAmountText, setHomeDepositAmountText\] = useState\(''\)/)
    assert.match(page, /const \[homeDepositSubmitting, setHomeDepositSubmitting\] = useState\(false\)/)
    assert.match(page, /const \[homeOrderClaimSubmitting, setHomeOrderClaimSubmitting\] = useState\(false\)/)
    assert.match(page, /const \[homeOrderClaiming, setHomeOrderClaiming\] = useState<HomeOrder \| undefined>\(undefined\)/)
    assert.match(page, /const \[inviteAddressText, setInviteAddressText\] = useState\(''\)/)
    assert.match(page, /const \[showInviteAddressPopup, setShowInviteAddressPopup\] = useState\(false\)/)
    assert.match(page, /const isReferralBound = useUserStore\(\(state\) => state\.isReferralBound\)/)
    assert.match(page, /const setReferralBound = useUserStore\(\(state\) => state\.setReferralBound\)/)
    assert.match(page, /const \[usdtBalanceAmount, setUsdtBalanceAmount\] = useState\(0n\)/)
    assert.match(page, /setUsdtBalanceAmount\(0n\)/)
    assert.match(page, /setUsdtBalanceAmount\(balance\)/)
    assert.match(page, /const refreshHomeScreenData = useCallback\(\(\) => \{[\s\S]*setHomeOrderPageNo\(1\)[\s\S]*setHomeScreenRefreshVersion\(\(current\) => current \+ 1\)[\s\S]*\}, \[\]\)/)
    assert.match(page, /const stopHomeScreenRefreshTimer = useCallback\(\(\) => \{[\s\S]*window\.clearInterval\(homeScreenRefreshTimerRef\.current\)[\s\S]*homeScreenRefreshTimerRef\.current = undefined[\s\S]*\}, \[\]\)/)
    assert.match(page, /const startHomeScreenRefreshTimer = useCallback\(\(\) => \{[\s\S]*stopHomeScreenRefreshTimer\(\)[\s\S]*homeScreenRefreshTimerRef\.current = window\.setInterval\([\s\S]*refreshHomeScreenData,[\s\S]*HOME_SCREEN_REFRESH_INTERVAL_MS,[\s\S]*\)[\s\S]*\}, \[refreshHomeScreenData, stopHomeScreenRefreshTimer\]\)/)
    assert.match(page, /useEffect\(\(\) => \{[\s\S]*startHomeScreenRefreshTimer\(\)[\s\S]*return stopHomeScreenRefreshTimer[\s\S]*\}, \[startHomeScreenRefreshTimer, stopHomeScreenRefreshTimer\]\)/)
    assert.match(page, /\}, \[walletAddress, homeScreenRefreshVersion\]\)/)
    assert.match(page, /async function loadHomeDepositLimits\(\) \{[\s\S]*const \[minimum, maximum\] = await Promise\.all\(\[[\s\S]*readAigoProjectMinDepositUsdt\(\),[\s\S]*readAigoProjectMaxDepositUsdt\(\),[\s\S]*\]\)[\s\S]*setHomeDepositMinimum\(minimum\)[\s\S]*setHomeDepositMaximum\(maximum\)[\s\S]*setHomeDepositLimitsLoaded\(true\)/)
    assert.match(page, /\}, \[homeScreenRefreshVersion\]\)/)
    assert.match(page, /getOrders\([\s\S]*createHomeOrderListParams\(activeOrderStatus, homeOrderPageNo\)[\s\S]*\)/)
    assert.match(page, /const nextHomeOrders = response\.orders\.map\(\(order\) => mapApiOrderToHomeOrder\([\s\S]*?order,[\s\S]*?activeOrderStatus === 'active'/)
    assert.match(page, /function sortHomeOrderIndexes\(indexes: readonly bigint\[\]\): bigint\[\] \{[\s\S]*return \[\.\.\.indexes\]\.sort\(\(left, right\) => \{[\s\S]*left < right[\s\S]*left > right/)
    assert.match(page, /setStaticRewardOrderIndexes\(sortHomeOrderIndexes\([\s\S]*response\.orders\.map\(\(order\) => BigInt\(order\.index\)\)[\s\S]*\)\)/)
    assert.match(page, /if \(activeOrderStatus === 'active'\) return[\s\S]*async function loadInactiveHomeQuotaProgress\(\) \{[\s\S]*getOrders\(createHomeOrderListParams\('active', 1\)\)[\s\S]*let totalClaimedAmount = 0n[\s\S]*let totalAmount = '0'[\s\S]*for \(const order of response\.orders\) \{[\s\S]*const \{ claimedUsdt \} = await readAigoProjectOrder\([\s\S]*walletAddress as Address,[\s\S]*BigInt\(order\.index\),[\s\S]*\)[\s\S]*totalClaimedAmount \+= claimedUsdt[\s\S]*totalAmount = addDecimalNumbers\(totalAmount, order\.total_amount\)[\s\S]*setHomeQuotaProgress\(\{[\s\S]*amount:\s*formatDappAmountUnits\(totalClaimedAmount\),[\s\S]*totalAmount,[\s\S]*loading:\s*false/)
    assert.match(page, /\}, \[activeOrderStatus, walletAddress, homeScreenRefreshVersion\]\)/)
    assert.match(page, /if \(activeOrderStatus === 'active'\) \{[\s\S]*setHomeQuotaProgress\(\{[\s\S]*amount:\s*'0',[\s\S]*totalAmount:\s*'0',[\s\S]*loading:\s*true,[\s\S]*\}\)[\s\S]*setStaticRewardTokenAmount\(0n\)/)
    assert.match(page, /if \(activeOrderStatus === 'active'\) \{[\s\S]*if \(response\.orders\.length > 0\) \{[\s\S]*void logActiveOrderPendingStaticRewards\(response\.orders\)[\s\S]*\} else if \(isCurrent\) \{[\s\S]*setStaticRewardTokenAmount\(0n\)[\s\S]*setStaticRewardTokenLoading\(false\)[\s\S]*\}[\s\S]*void logHomeOrderContractProgress\(response\.orders\)[\s\S]*\}/)
    assert.match(page, /async function logActiveOrderPendingStaticRewards\(orders: ApiOrder\[\]\) \{[\s\S]*const indexes = sortHomeOrderIndexes\([\s\S]*orders\.map\(\(order\) => BigInt\(order\.index\)\)[\s\S]*\)[\s\S]*const \[, staticRewardAmount\] = await readAigoProjectPendingStaticRewards\(indexes\)[\s\S]*setStaticRewardTokenAmount\(staticRewardAmount\)[\s\S]*setStaticRewardTokenLoading\(false\)[\s\S]*for \(const order of orders\) \{[\s\S]*const indexes = \[BigInt\(order\.index\)\][\s\S]*await readAigoProjectPendingStaticRewards\(indexes\)[\s\S]*claimableLoading: false/)
    assert.doesNotMatch(page, /totalStaticRewardAmount \+= claimableAmount/)
    assert.match(page, /async function logHomeOrderContractProgress\(orders: ApiOrder\[\]\) \{[\s\S]*let totalClaimedAmount = 0n[\s\S]*let totalAmount = '0'[\s\S]*for \(const order of orders\) \{[\s\S]*totalAmount = addDecimalNumbers\(totalAmount, order\.total_amount\)[\s\S]*const index = BigInt\(order\.index\)[\s\S]*const \{ claimedUsdt: releaseAmount \} = await readAigoProjectOrder\([\s\S]*walletAddress as Address,[\s\S]*index,[\s\S]*\)[\s\S]*totalClaimedAmount \+= releaseAmount[\s\S]*const releaseAmountText = formatDappAmountUnits\(releaseAmount\)[\s\S]*progressCurrentValue:\s*releaseAmountText,[\s\S]*progressCurrentText:\s*formatAmount\(releaseAmountText\),[\s\S]*progressLoading:\s*false[\s\S]*setHomeQuotaProgress\(\{[\s\S]*amount:\s*formatDappAmountUnits\(totalClaimedAmount\),[\s\S]*totalAmount,[\s\S]*loading:\s*false/)
    assert.match(page, /setHomeOrders\(\(current\) => homeOrderPageNo === 1 \? nextHomeOrders : current\.concat\(nextHomeOrders\)\)/)
    assert.match(page, /setHomeOrderHasNextPage\(activeOrderStatus === 'completed' && response\.orders\.length >= HOME_ORDER_PAGE_SIZE\)/)
    assert.match(page, /activeOrderStatus,[\s\S]*homeOrderPageNo,[\s\S]*homeScreenRefreshVersion,[\s\S]*walletAddress,[\s\S]*\]\)/)
    assert.match(page, /handleChangeOrderStatus/)
    assert.match(page, /setHomeOrderPageNo\(1\)/)
    assert.match(page, /handleLoadMoreHomeOrders/)
    assert.match(page, /setHomeOrderPageNo\(\(current\) => current \+ 1\)/)
    assert.match(page, /function handleOpenRewardDetail\(\) \{[\s\S]*pushRoute\(ROUTE_PATH\.homeRewardDetail\)[\s\S]*\}/)
    assert.match(page, /function handleUseAllHomeDepositAmount\(\) \{[\s\S]*if \(usdtBalanceAmount <= 0n\) \{[\s\S]*message\.warning\(t\('余额不足'\)\)[\s\S]*return[\s\S]*\}[\s\S]*setHomeDepositAmountText\(formatDappAmountUnits\(usdtBalanceAmount\)\)/)
    assert.match(page, /function handleOpenInviteAddressPopup\(\) \{[\s\S]*const referralCode = getReferralCode\(\)\.trim\(\)[\s\S]*setInviteAddressText\(referralCode\)[\s\S]*setShowInviteAddressPopup\(true\)/)
    assert.match(page, /function validateHomeDepositAmount\(\): bigint \| undefined \{[\s\S]*if \(!amountText\) \{[\s\S]*message\.warning\(t\('请输入金额'\)\)[\s\S]*return undefined[\s\S]*\}[\s\S]*if \(!homeDepositLimitsLoaded\) \{[\s\S]*message\.warning\(t\('入金额度加载中'\)\)[\s\S]*return undefined[\s\S]*\}[\s\S]*const amount = parseHomeDepositAmount\(amountText\)[\s\S]*if \(amount < homeDepositMinimum\) \{[\s\S]*message\.warning\(t\('入金金额低于最小限额'\)\)[\s\S]*return undefined[\s\S]*\}[\s\S]*if \(amount > homeDepositMaximum\) \{[\s\S]*message\.warning\(t\('入金金额超过最大限额'\)\)[\s\S]*return undefined[\s\S]*\}[\s\S]*if \(amount <= 0n \|\| amount > usdtBalanceAmount\) \{[\s\S]*message\.warning\(t\('余额不足'\)\)/)
    assert.match(page, /function handleSubmitHomeDeposit\(\) \{[\s\S]*const amount = validateHomeDepositAmount\(\)[\s\S]*if \(amount === undefined\) return[\s\S]*if \(!isReferralBound\) \{[\s\S]*handleOpenInviteAddressPopup\(\)[\s\S]*return[\s\S]*\}[\s\S]*void submitHomeDeposit\(amount\)/)
    assert.match(page, /async function handleConfirmHomeDepositWithInvite\(\) \{[\s\S]*if \(!referralAddress\) \{[\s\S]*message\.warning\(t\('请输入邀请地址'\)\)[\s\S]*return[\s\S]*\}[\s\S]*if \(!isAddress\(referralAddress\)\) \{[\s\S]*message\.warning\(t\('邀请地址格式错误'\)\)[\s\S]*return[\s\S]*\}[\s\S]*await submitHomeDeposit\(amount, referralAddress as Address\)/)
    assert.match(page, /async function submitHomeDeposit\([\s\S]*amount: bigint,[\s\S]*referralAddress\?: Address,[\s\S]*\) \{[\s\S]*stopHomeScreenRefreshTimer\(\)[\s\S]*setHomeDepositSubmitting\(true\)[\s\S]*await submitHomeDepositOrder\(\{[\s\S]*amount,[\s\S]*walletAddress: walletAddress as Address,[\s\S]*referralAddress,[\s\S]*\}\)[\s\S]*if \(referralAddress\) \{[\s\S]*setReferralBound\(true\)[\s\S]*\}[\s\S]*await waitForDappContractDataSync\(\)[\s\S]*setHomeDepositAmountText\(''\)[\s\S]*setShowInviteAddressPopup\(false\)[\s\S]*refreshHomeScreenData\(\)[\s\S]*message\.success\(t\('操作成功'\)\)[\s\S]*setHomeDepositSubmitting\(false\)[\s\S]*startHomeScreenRefreshTimer\(\)/)
    assert.match(page, /async function handleConfirmHomeOrderClaim\(\) \{[\s\S]*stopHomeScreenRefreshTimer\(\)[\s\S]*setHomeOrderClaimSubmitting\(true\)[\s\S]*await writeAigoProjectClaimStaticRewards\(\[BigInt\(homeOrderClaiming\.contractIndex\)\]\)[\s\S]*await waitForDappContractDataSync\(\)[\s\S]*setHomeOrderClaiming\(undefined\)[\s\S]*refreshHomeScreenData\(\)[\s\S]*message\.success\(t\('操作成功'\)\)[\s\S]*setHomeOrderClaimSubmitting\(false\)[\s\S]*startHomeScreenRefreshTimer\(\)/)
    assert.match(page, /function handleOpenStaticRewardClaimPopup\(\) \{[\s\S]*if \(staticRewardTokenAmount <= 0n \|\| staticRewardOrderIndexes\.length === 0\) \{[\s\S]*message\.warning\(t\('可提取收益不足'\)\)[\s\S]*return[\s\S]*\}[\s\S]*setShowStaticRewardClaimPopup\(true\)/)
    assert.match(page, /async function handleConfirmStaticRewardClaim\(\) \{[\s\S]*stopHomeScreenRefreshTimer\(\)[\s\S]*setHomeOrderClaimSubmitting\(true\)[\s\S]*await writeAigoProjectClaimStaticRewards\(sortHomeOrderIndexes\(staticRewardOrderIndexes\)\)[\s\S]*await waitForDappContractDataSync\(\)[\s\S]*setShowStaticRewardClaimPopup\(false\)[\s\S]*refreshHomeScreenData\(\)[\s\S]*message\.success\(t\('操作成功'\)\)[\s\S]*setHomeOrderClaimSubmitting\(false\)[\s\S]*startHomeScreenRefreshTimer\(\)/)
    assert.doesNotMatch(page, /HOME_ORDER_LIST/)
    assert.match(page, /<section className="home-page"/)
    assert.match(page, /<ContractLoading show=\{homeDepositSubmitting \|\| homeOrderClaimSubmitting\} \/>/)
    assert.match(page, /home-page__bg/)
    assert.match(page, /home-page__hero/)
    assert.match(page, /home-page__cooperation-card/)
    assert.match(page, /t\('加入生态协作'\)/)
    assert.match(page, /t\('额度进度'\)/)
    assert.match(page, /homeQuotaProgress\.loading \? \([\s\S]*<Icon name="loading" className="size-24 blue" ariaLabel=\{t\('已入金额度加载中'\)\} \/>[\s\S]*<Icon name="loading" className="size-24 blue" ariaLabel=\{t\('总额度加载中'\)\} \/>[\s\S]*\) : \([\s\S]*homeQuotaProgress\.amount[\s\S]*homeQuotaProgress\.totalAmount/)
    assert.match(page, /<ProgressBar[\s\S]*currentValue=\{homeQuotaProgress\.amount\}[\s\S]*totalValue=\{homeQuotaProgress\.totalAmount\}/)
    assert.match(page, /className="[^"]*home-page__progress-bar[^"]*"/)
    assert.match(page, /home-page__deposit/)
    assert.match(page, /t\('入金金额'\)/)
    assert.match(page, /usdtBalanceText/)
    assert.match(page, /dynamicRewardTokenText/)
    assert.match(page, /HOME_TOKEN_SYMBOL/)
    assert.doesNotMatch(page, /PROJECT_TOKEN\.platform\.symbol/)
    assert.doesNotMatch(page, /52,42/)
    assert.match(page, /t\('全部'\)/)
    assert.match(page, /const homeDepositPlaceholder = t\('单次入金 \{\{min\}\}～\{\{max\}\}'/)
    assert.match(page, /<input[\s\S]*className="[^"]*home-page__deposit-input[^"]*"[\s\S]*placeholder=\{homeDepositPlaceholder\}/)
    assert.match(page, /value=\{homeDepositAmountText\}/)
    assert.match(page, /onChange=\{\(event\) => setHomeDepositAmountText\(event\.target\.value\)\}/)
    assert.match(page, /className="home-page__deposit-all blue size-22 ml-8"[\s\S]*onClick=\{handleUseAllHomeDepositAmount\}/)
    assert.doesNotMatch(page, /<div className="[^"]*home-page__deposit-input/)
    assert.match(page, /className="home-page__deposit-submit size-28 bold-5 mt-30"[\s\S]*onClick=\{handleSubmitHomeDeposit\}[\s\S]*t\('确认'\)/)
    assert.doesNotMatch(page, /mr10/)
    assert.match(page, /homeOrders\.map/)
    assert.match(page, /home-page__income-card/)
    assert.match(page, /src=\{incomeIcon\}/)
    assert.doesNotMatch(page, /↗/)
    assert.match(page, /t\('一键领取静态收益'\)/)
    assert.match(page, /staticRewardTokenLoading \? \([\s\S]*<Icon name="loading" className="size-40 blue" ariaLabel=\{t\('静态收益加载中'\)\} \/>[\s\S]*\) : \([\s\S]*formatAmount\(formatDappAmountUnits\(staticRewardTokenAmount\)\)/)
    assert.doesNotMatch(page, /226,567/)
    assert.match(page, /home-page__income-static[\s\S]*onClick=\{handleOpenStaticRewardClaimPopup\}/)
    assert.match(page, /t\('一键领取动态收益'\)/)
    assert.match(page, /readAigoProjectPendingDynamicReward\(\s*walletAddress as Address,\s*\)/)
    assert.match(page, /const \[dynamicRewardTokenAmount, setDynamicRewardTokenAmount\] = useState\(0n\)/)
    assert.match(page, /const \[, dynamicRewardTokenAmount\]/)
    assert.match(page, /setDynamicRewardTokenAmount\(0n\)/)
    assert.match(page, /setDynamicRewardTokenAmount\(dynamicRewardTokenAmount\)/)
    assert.match(page, /setDynamicRewardTokenText\(formatAmount\(formatDappAmountUnits\(dynamicRewardTokenAmount\)\)\)/)
    assert.doesNotMatch(page, /canClaimDynamicReward/)
    assert.doesNotMatch(page, /\{canClaimDynamicReward \? \(/)
    assert.match(page, /home-page__income-dynamic[\s\S]*className="home-page__claim-button home-page__claim-button--muted size-24 bold-7"[\s\S]*onClick=\{handleOpenDynamicRewardClaimPopup\}/)
    assert.match(page, /function handleOpenDynamicRewardClaimPopup\(\) \{[\s\S]*if \(dynamicRewardTokenAmount <= 0n\) \{[\s\S]*message\.warning\(t\('可提取收益不足'\)\)[\s\S]*return[\s\S]*\}[\s\S]*setShowDynamicRewardClaimPopup\(true\)/)
    assert.match(page, /handleConfirmDynamicRewardClaim/)
    assert.match(page, /async function handleConfirmDynamicRewardClaim\(\) \{[\s\S]*stopHomeScreenRefreshTimer\(\)[\s\S]*await claimDynamicReward\(\)[\s\S]*handleCloseDynamicRewardClaimPopup\(\)[\s\S]*refreshHomeScreenData\(\)[\s\S]*startHomeScreenRefreshTimer\(\)/)
    assert.match(page, /function claimDynamicReward\(\): Promise<void>/)
    assert.match(page, /void handleConfirmDynamicRewardClaim\(\)/)
    assert.match(page, /\{dynamicRewardTokenText\}/)
    assert.match(page, /\{HOME_TOKEN_SYMBOL\}/)
    assert.match(page, /showDynamicRewardClaimPopup/)
    assert.match(page, /showInviteAddressPopup/)
    assert.match(page, /<ConfirmPopup[\s\S]*show=\{showDynamicRewardClaimPopup\}[\s\S]*message=\{t\('确认要提取吗？'\)\}[\s\S]*onConfirm=\{\(\) => void handleConfirmDynamicRewardClaim\(\)\}/)
    assert.match(page, /<ConfirmPopup[\s\S]*show=\{homeOrderClaiming !== undefined\}[\s\S]*message=\{t\('确认要提取吗？'\)\}[\s\S]*onConfirm=\{\(\) => void handleConfirmHomeOrderClaim\(\)\}/)
    assert.match(page, /<ConfirmPopup[\s\S]*show=\{showStaticRewardClaimPopup\}[\s\S]*message=\{t\('确认要提取吗？'\)\}[\s\S]*submitting=\{homeOrderClaimSubmitting\}[\s\S]*onConfirm=\{\(\) => void handleConfirmStaticRewardClaim\(\)\}/)
    assert.match(page, /title=\{<span className="home-page__invite-popup-title size-40 bold-6">\{t\('确认邀请地址'\)\}<\/span>\}/)
    assert.match(page, /className="home-page__invite-input size-28 mt-40"/)
    assert.match(page, /placeholder=\{t\('请输入邀请地址'\)\}/)
    assert.match(page, /value=\{inviteAddressText\}/)
    assert.match(page, /onChange=\{\(event\) => setInviteAddressText\(event\.target\.value\)\}/)
    assert.match(page, /className="home-page__invite-confirm size-28 bold-6 mt-40"/)
    assert.match(page, /onClick=\{\(\) => void handleConfirmHomeDepositWithInvite\(\)\}/)
    assert.match(page, />\s*\{t\('确认入金'\)\}\s*</)
    assert.match(page, /className="home-page__income-detail blue size-24 mt-16"[\s\S]*onClick=\{handleOpenRewardDetail\}[\s\S]*t\('查看领取明细'\)/)
    assert.doesNotMatch(page, /<div className="home-page__income-detail/)
    assert.match(page, /t\('协作订单'\)/)
    assert.match(page, /进行中/)
    assert.match(page, /已完成/)
    assert.match(page, /<SegmentedTabs[\s\S]*options=\{homeOrderStatusTabs\}[\s\S]*value=\{activeOrderStatus\}[\s\S]*onChange=\{handleChangeOrderStatus\}/)
    assert.match(page, /ariaLabel=\{t\('协作订单状态'\)\}/)
    assert.match(page, /className="home-page__status-tabs mt-28"/)
    assert.doesNotMatch(page, /HOME_ORDER_STATUS_TABS\.map/)
    assert.doesNotMatch(page, /home-page__status-tab-indicator/)
    assert.doesNotMatch(page, /home-page__status-tab--active/)
    assert.doesNotMatch(page, /home-page__status-tab--inactive/)
    assert.match(page, /home-page__order-list/)
    assert.match(page, /<Empty showGap=\{false\} className="home-page__order-empty" \/>/)
    assert.doesNotMatch(page, /<Empty text=/)
    assert.match(page, /<InfiniteScroll[\s\S]*loading=\{homeOrderLoading\}[\s\S]*hasMore=\{homeOrderHasNextPage\}[\s\S]*onLoadMore=\{handleLoadMoreHomeOrders\}/)
    assert.match(page, /className="home-page__order-scroll mt-30"/)
    assert.doesNotMatch(page, /home-page__order-pagination/)
    assert.doesNotMatch(page, /home-page__order-page-button/)
    assert.doesNotMatch(page, /home-page__order-page-text/)
    assert.match(page, /t\('协作额度'\)/)
    assert.match(page, /src=\{usdtIcon\}/)
    assert.doesNotMatch(page, /home-page__token-icon[\s\S]*T/)
    assert.match(page, /t\('进度\(\{\{multiple\}\}倍\)', \{ multiple: order\.progressMultipleText \}\)/)
    assert.match(page, /\{\/\* 总释放、协作收益等待确认合约返回映射后再展示。 \*\/\}/)
    assert.match(page, /\{order\.status === 'active' \? \([\s\S]*<div className="home-page__order-line mt-20" \/>[\s\S]*<div className="home-page__order-info mt-28">[\s\S]*t\('可领取'\)[\s\S]*\) : null\}/)
    assert.match(page, /t\('可领取'\)/)
    assert.match(page, /order\.claimableText/)
    assert.match(page, /order\.claimableLoading \? \([\s\S]*<Icon name="loading" className="size-24 blue mr-20" ariaLabel=\{t\('可领取收益加载中'\)\} \/>/)
    assert.match(page, /order\.canClaim \? \([\s\S]*<button/)
    assert.match(page, /onClick=\{\(\) => handleOpenHomeOrderClaim\(order\)\}/)
    assert.match(page, /order\.progressCurrentValue/)
    assert.match(page, /order\.progressCurrentText/)
    assert.match(page, /className="home-page__order-summary"/)
    assert.match(page, /className="[^"]*home-page__order-progress[^"]*"/)
    assert.match(page, /className="home-page__order-progress-text size-24 tr mt-10"/)
    assert.match(page, /<div className="[^"]*home-page__order-progress[^"]*">[\s\S]*<ProgressBar[\s\S]*currentValue=\{order\.progressCurrentValue\}[\s\S]*totalValue=\{order\.progressTotalValue\}[\s\S]*aria-label=\{t\('订单进度'\)\}[\s\S]*order\.progressLoading \? \([\s\S]*<Icon name="loading" className="size-24 blue" ariaLabel=\{t\('订单进度加载中'\)\} \/>[\s\S]*\) : \([\s\S]*order\.progressCurrentText[\s\S]*t\('进度\(\{\{multiple\}\}倍\)', \{ multiple: order\.progressMultipleText \}\)/)
    assert.doesNotMatch(page, /calculatePercentage/)
    assert.doesNotMatch(page, /style=/)

    assert.match(styles, /\.home-page\s*\{/)
    assert.match(styles, /min-height:\s*3000px/)
    assert.match(styles, /&__bg/)
    assert.match(styles, /&__hero/)
    assert.match(styles, /&__cooperation-card/)
    assert.match(styles, /background-image:\s*url\("@\/assets\/home\/card-bg\.png"\)/)
    assert.match(styles, /&__progress-bar[\s\S]*height:\s*24px/)
    assert.match(styles, /&__deposit-input/)
    assert.match(styles, /&::placeholder/)
    assert.match(styles, /&__deposit-submit/)
    assert.match(styles, /&__deposit-submit[\s\S]*@include full-button\(/)
    assert.match(styles, /&__invite-popup-title[\s\S]*@include gradient-word\(var\(--app-btn-bg\)\)/)
    assert.match(styles, /&__invite-input/)
    assert.match(styles, /&__invite-confirm[\s\S]*@include full-button\(80px,\s*999px\)/)
    assert.match(styles, /--app-progress-color:\s*linear-gradient\(90deg,\s*#3760F9 0%,\s*#0090FF 100%\)/)
    assert.match(styles, /&__income-card/)
    assert.match(styles, /background-image:\s*url\("@\/assets\/home\/income-card\.png"\)/)
    assert.match(styles, /&__income-static/)
    assert.match(styles, /&__income-dynamic/)
    assert.doesNotMatch(styles, /&__mini-token/)
    assert.doesNotMatch(styles, /&__token-icon/)
    assert.match(styles, /&__claim-button[\s\S]*@include auto-button\(/)
    assert.doesNotMatch(styles, /&__claim-popup/)
    assert.doesNotMatch(styles, /auto-button\(70px,\s*999px,\s*210px\)/)
    assert.match(styles, /&__order-claim[\s\S]*@include auto-button\(/)
    assert.match(styles, /&__section-title-line/)
    assert.doesNotMatch(styles, /&__status-tabs/)
    assert.doesNotMatch(styles, /&__status-tab/)
    assert.match(styles, /&__order-card/)
    assert.match(styles, /&__order-summary\s*\{[\s\S]*min-width:\s*0/)
    assert.doesNotMatch(styles, /&__order-card\s*\{[\s\S]*?min-height:\s*437px/)
    assert.match(styles, /&__order-card\s*\{[\s\S]*?padding:\s*30px/)
    assert.match(styles, /&__order-progress/)
    assert.doesNotMatch(styles, /&__order-pagination/)
    assert.doesNotMatch(styles, /&__order-page-button/)
})

test('home page displays every token amount as Token without touching platform coin copy', async () => {
    const page = await readFile('src/pages/main/home/HomePage.tsx', 'utf8')

    assert.match(page, /const HOME_TOKEN_SYMBOL = PROJECT_TOKEN\.usdt\.symbol/)
    assert.doesNotMatch(page, /PROJECT_TOKEN\.platform\.symbol/)
    assert.match(page, /formatHomeOrderTokenText\(value: string\): string \{[\s\S]*HOME_TOKEN_SYMBOL/)
    assert.match(page, /incomeText:\s*`\$\{TOKEN_BALANCE_EMPTY_TEXT\} \$\{HOME_TOKEN_SYMBOL\}`/)
    assert.match(page, /claimableText:\s*`\$\{TOKEN_BALANCE_EMPTY_TEXT\} \$\{HOME_TOKEN_SYMBOL\}`/)
    assert.match(page, /homeQuotaProgress\.totalAmount\)}\{HOME_TOKEN_SYMBOL\}/)
    assert.match(page, /order\.progressTotalText\}\{HOME_TOKEN_SYMBOL\}/)
})
