import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('home page builds the full static page from semantic blocks and shared progress bars', async () => {
    const [page, styles] = await Promise.all([
        readFile('src/pages/main/home/HomePage.tsx', 'utf8'),
        readFile('src/pages/main/home/HomePage.scss', 'utf8'),
    ])

    assert.match(page, /import \{ ProgressBar \} from '@\/components\/ProgressBar'/)
    assert.match(page, /import \{ SegmentedTabs \} from '@\/components\/SegmentedTabs'/)
    assert.match(page, /import \{ useState \} from 'react'/)
    assert.match(page, /incomeIcon from '@\/assets\/home\/income\.png'/)
    assert.match(page, /usdtIcon from '@\/assets\/common\/usdt\.png'/)
    assert.match(page, /type HomeOrderStatus = 'active' \| 'completed'/)
    assert.match(page, /HOME_ORDER_STATUS_TABS/)
    assert.match(page, /const \[activeOrderStatus, setActiveOrderStatus\] = useState<HomeOrderStatus>\('active'\)/)
    assert.match(page, /visibleHomeOrders = HOME_ORDER_LIST\.filter\(\(order\) => order\.status === activeOrderStatus\)/)
    assert.match(page, /<section className="home-page"/)
    assert.match(page, /home-page__bg/)
    assert.match(page, /home-page__hero/)
    assert.match(page, /home-page__cooperation-card/)
    assert.match(page, /加入生态协作/)
    assert.match(page, /额度进度/)
    assert.match(page, /<ProgressBar[\s\S]*currentValue="128\.88"[\s\S]*totalValue="200"/)
    assert.match(page, /className="[^"]*home-page__progress-bar[^"]*"/)
    assert.match(page, /home-page__deposit/)
    assert.match(page, /入金金额/)
    assert.match(page, /52,42/)
    assert.match(page, /Token/)
    assert.match(page, /全部/)
    assert.match(page, /<input[\s\S]*className="[^"]*home-page__deposit-input[^"]*"[\s\S]*placeholder="请输入购买数量"/)
    assert.doesNotMatch(page, /<div className="[^"]*home-page__deposit-input/)
    assert.match(page, /确认/)
    assert.doesNotMatch(page, /mr10/)
    assert.match(page, /visibleHomeOrders\.map/)
    assert.match(page, /home-page__income-card/)
    assert.match(page, /src=\{incomeIcon\}/)
    assert.doesNotMatch(page, /↗/)
    assert.match(page, /一键领取静态收益/)
    assert.match(page, /一键领取动态收益/)
    assert.match(page, /查看领取明细/)
    assert.match(page, /协作订单/)
    assert.match(page, /进行中/)
    assert.match(page, /已完成/)
    assert.match(page, /<SegmentedTabs[\s\S]*options=\{HOME_ORDER_STATUS_TABS\}[\s\S]*value=\{activeOrderStatus\}[\s\S]*onChange=\{setActiveOrderStatus\}/)
    assert.match(page, /ariaLabel="协作订单状态"/)
    assert.match(page, /className="home-page__status-tabs mt-28"/)
    assert.doesNotMatch(page, /HOME_ORDER_STATUS_TABS\.map/)
    assert.doesNotMatch(page, /home-page__status-tab-indicator/)
    assert.doesNotMatch(page, /home-page__status-tab--active/)
    assert.doesNotMatch(page, /home-page__status-tab--inactive/)
    assert.match(page, /home-page__order-list/)
    assert.match(page, /协作额度/)
    assert.match(page, /src=\{usdtIcon\}/)
    assert.doesNotMatch(page, /home-page__token-icon[\s\S]*T/)
    assert.match(page, /进度\(3倍\)/)
    assert.match(page, /总释放/)
    assert.match(page, /协作收益/)
    assert.match(page, /可领取/)
    assert.match(page, /order\.claimable/)
    assert.match(page, /order\.progressCurrent/)
    assert.match(page, /<div className="home-page__order-progress">[\s\S]*<ProgressBar[\s\S]*<div className="size-24 tr mt-8">[\s\S]*order\.progressCurrent[\s\S]*进度\(3倍\)/)
    assert.doesNotMatch(page, /calculatePercentage/)
    assert.doesNotMatch(page, /style=/)

    assert.match(styles, /\.home-page\s*\{/)
    assert.match(styles, /min-height:\s*3000px/)
    assert.match(styles, /&__bg/)
    assert.match(styles, /&__hero/)
    assert.match(styles, /&__cooperation-card/)
    assert.match(styles, /background-image:\s*url\("@\/assets\/home\/card-bg\.png"\)/)
    assert.match(styles, /&__progress-bar[\s\S]*height:\s*24px/)
    assert.match(styles, /&__deposit-input/)
    assert.match(styles, /&::placeholder/)
    assert.match(styles, /&__deposit-submit/)
    assert.match(styles, /&__deposit-submit[\s\S]*@include full-button\(/)
    assert.match(styles, /--app-progress-color:\s*linear-gradient\(90deg,\s*#3760F9 0%,\s*#0090FF 100%\)/)
    assert.match(styles, /&__income-card/)
    assert.match(styles, /background-image:\s*url\("@\/assets\/home\/income-card\.png"\)/)
    assert.match(styles, /&__income-static/)
    assert.match(styles, /&__income-dynamic/)
    assert.doesNotMatch(styles, /&__mini-token/)
    assert.doesNotMatch(styles, /&__token-icon/)
    assert.match(styles, /&__claim-button[\s\S]*@include auto-button\(/)
    assert.match(styles, /&__order-claim[\s\S]*@include auto-button\(/)
    assert.match(styles, /&__section-title-line/)
    assert.doesNotMatch(styles, /&__status-tabs/)
    assert.doesNotMatch(styles, /&__status-tab/)
    assert.match(styles, /&__order-card/)
    assert.match(styles, /&__order-progress/)
})
