import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('swap page builds the static exchange screen with local interactions', async () => {
    const [page, styles] = await Promise.all([
        readFile('src/pages/main/swap/SwapPage.tsx', 'utf8'),
        readFile('src/pages/main/swap/SwapPage.scss', 'utf8'),
    ])

    assert.match(page, /import \{[\s\S]*useEffect,[\s\S]*useState,[\s\S]*\} from 'react'/)
    assert.match(page, /import \{ useTranslation \} from 'react-i18next'/)
    assert.match(page, /import \{[\s\S]*APP_CONFIG,[\s\S]*PROJECT_TOKEN,[\s\S]*\} from '@\/config'/)
    assert.match(page, /import type \{ Address \} from 'viem'/)
    assert.match(page, /formatDappAmountUnits/)
    assert.match(page, /parseDappAmountUnits/)
    assert.match(page, /readErc20Balance/)
    assert.match(page, /waitForDappContractDataSync/)
    assert.match(page, /readAigoRouterAmountsOut/)
    assert.match(page, /getAigoTokenAddress/)
    assert.match(page, /getUsdtAddress/)
    assert.match(page, /ContractLoading/)
    assert.match(page, /Empty/)
    assert.match(page, /InfiniteScroll/)
    assert.match(page, /message/)
    assert.match(page, /submitSwapOrder/)
    assert.match(page, /getSwapLogs/)
    assert.match(page, /import type \{ SwapLog \} from '@\/features\/swap\/types\.ts'/)
    assert.match(page, /useDappStore/)
    assert.match(page, /formatQuantity/)
    assert.match(page, /bg from '@\/assets\/swap\/bg\.png'/)
    assert.match(page, /swapIcon from '@\/assets\/swap\/swap\.png'/)
    assert.match(page, /walletIcon from '@\/assets\/home\/wallet\.png'/)
    assert.match(page, /usdtIcon from '@\/assets\/common\/usdt\.png'/)
    assert.match(page, /const appLogoUrl = `\$\{APP_CONFIG\.routeBase\}brand\/app-logo\.png`/)
    assert.match(page, /type SwapTokenSymbol = \(typeof PROJECT_TOKEN\)\[keyof typeof PROJECT_TOKEN\]\['symbol'\]/)
    assert.match(page, /SWAP_TOKEN_MAP/)
    assert.doesNotMatch(page, /const SWAP_RECORD_LIST/)
    assert.match(page, /const TOKEN_BALANCE_EMPTY_TEXT = '0'/)
    assert.match(page, /const SWAP_QUOTE_DEBOUNCE_MS = 500/)
    assert.match(page, /const SWAP_RECORD_PAGE_SIZE = 20/)
    assert.match(page, /const SWAP_BPS_DENOMINATOR = 10000n/)
    assert.match(page, /const SWAP_SLIPPAGE_BPS = 500n/)
    assert.match(page, /function calculateSwapMinUsdtOut\(quotedUsdt: bigint\): bigint/)
    assert.match(page, /quotedUsdt \* \(SWAP_BPS_DENOMINATOR - SWAP_SLIPPAGE_BPS\) \/ SWAP_BPS_DENOMINATOR/)
    assert.match(page, /function normalizeSwapQuoteInput\(value: string\): string/)
    assert.match(page, /function mapSwapLogToRecord\(log: SwapLog\): SwapRecord/)
    assert.match(page, /fromAmount: `\$\{formatQuantity\(log\.aigo_amount\)\} \$\{PROJECT_TOKEN\.platform\.symbol\}`/)
    assert.match(page, /toAmount: `\$\{formatQuantity\(log\.usdt_amount\)\} \$\{PROJECT_TOKEN\.usdt\.symbol\}`/)
    assert.match(page, /date: log\.created_at/)
    assert.doesNotMatch(page, /feeAmount/)
    assert.doesNotMatch(page, /txId/)
    assert.match(page, /const \[swapAmount, setSwapAmount\] = useState\(''\)/)
    assert.match(page, /const \[quotedUsdtText, setQuotedUsdtText\] = useState\(TOKEN_BALANCE_EMPTY_TEXT\)/)
    assert.match(page, /const \[quotedSwapAmountIn, setQuotedSwapAmountIn\] = useState\(0n\)/)
    assert.match(page, /const \[swapMinUsdtOutAmount, setSwapMinUsdtOutAmount\] = useState\(0n\)/)
    assert.match(page, /const \[swapSubmitting, setSwapSubmitting\] = useState\(false\)/)
    assert.match(page, /const \[platformTokenBalanceAmount, setPlatformTokenBalanceAmount\] = useState\(0n\)/)
    assert.match(page, /const \[platformTokenBalanceRefreshVersion, setPlatformTokenBalanceRefreshVersion\] = useState\(0\)/)
    assert.match(page, /const \[swapRecords, setSwapRecords\] = useState<SwapRecord\[\]>\(\[\]\)/)
    assert.match(page, /const \[swapRecordPageNo, setSwapRecordPageNo\] = useState\(1\)/)
    assert.match(page, /const \[swapRecordLoading, setSwapRecordLoading\] = useState\(false\)/)
    assert.match(page, /const \[swapRecordHasNextPage, setSwapRecordHasNextPage\] = useState\(false\)/)
    assert.match(page, /const \[swapRecordRefreshVersion, setSwapRecordRefreshVersion\] = useState\(0\)/)
    assert.match(page, /const walletAddress = useDappStore\(\(state\) => state\.walletAddress\)/)
    assert.match(page, /const \[platformTokenBalanceText, setPlatformTokenBalanceText\] = useState\(TOKEN_BALANCE_EMPTY_TEXT\)/)
    assert.match(page, /const \[platformTokenBalanceValue, setPlatformTokenBalanceValue\] = useState\(TOKEN_BALANCE_EMPTY_TEXT\)/)
    assert.match(page, /const fromToken = SWAP_TOKEN_MAP\[PROJECT_TOKEN\.platform\.symbol\]/)
    assert.match(page, /const toToken = SWAP_TOKEN_MAP\[PROJECT_TOKEN\.usdt\.symbol\]/)
    assert.doesNotMatch(page, /isDirectionReversed/)
    assert.doesNotMatch(page, /setIsDirectionReversed/)
    assert.match(page, /readErc20Balance\(\s*getAigoTokenAddress\(\),\s*walletAddress as Address,\s*\)/)
    assert.match(page, /setPlatformTokenBalanceValue\(formatDappAmountUnits\(balance\)\)/)
    assert.match(page, /setPlatformTokenBalanceText\(formatQuantity\(formatDappAmountUnits\(balance\)\)\)/)
    assert.match(page, /setPlatformTokenBalanceAmount\(balance\)/)
    assert.match(page, /setPlatformTokenBalanceText\(TOKEN_BALANCE_EMPTY_TEXT\)/)
    assert.match(page, /\}, \[walletAddress, platformTokenBalanceRefreshVersion\]\)/)
    assert.match(page, /window\.setTimeout\(\(\) => \{/)
    assert.match(page, /SWAP_QUOTE_DEBOUNCE_MS/)
    assert.match(page, /window\.clearTimeout\(quoteTimer\)/)
    assert.match(page, /parseDappAmountUnits\(normalizedSwapAmount\)/)
    assert.match(page, /readAigoRouterAmountsOut\(\s*swapAmountIn,\s*\[\s*getAigoTokenAddress\(\),\s*getUsdtAddress\(\),\s*\],\s*\)/)
    assert.match(page, /const quotedUsdt = amountsOut\[1\] \?\? 0n/)
    assert.match(page, /const minUsdtOut = calculateSwapMinUsdtOut\(quotedUsdt\)/)
    assert.match(page, /setQuotedSwapAmountIn\(swapAmountIn\)/)
    assert.match(page, /setSwapMinUsdtOutAmount\(minUsdtOut\)/)
    assert.match(page, /setQuotedUsdtText\(formatQuantity\(formatDappAmountUnits\(minUsdtOut\)\)\)/)
    assert.match(page, /setQuotedUsdtText\(TOKEN_BALANCE_EMPTY_TEXT\)/)
    assert.match(page, /getSwapLogs\(\{[\s\S]*page_no: swapRecordPageNo,[\s\S]*page_size: SWAP_RECORD_PAGE_SIZE,[\s\S]*\}\)/)
    assert.match(page, /const nextSwapRecords = response\.swap_logs\.map\(mapSwapLogToRecord\)/)
    assert.match(page, /setSwapRecords\(\(current\) => swapRecordPageNo === 1 \? nextSwapRecords : current\.concat\(nextSwapRecords\)\)/)
    assert.match(page, /setSwapRecordHasNextPage\(response\.swap_logs\.length >= SWAP_RECORD_PAGE_SIZE\)/)
    assert.match(page, /\}, \[swapRecordPageNo, swapRecordRefreshVersion\]\)/)
    assert.match(page, /function handleLoadMoreSwapRecords\(\)/)
    assert.match(page, /if \(swapRecordLoading \|\| !swapRecordHasNextPage\) return/)
    assert.match(page, /setSwapRecordPageNo\(\(current\) => current \+ 1\)/)
    assert.match(page, /function validateSwapAmount\(\): bigint \| undefined/)
    assert.match(page, /message\.warning\(t\('请输入金额'\)\)/)
    assert.match(page, /message\.warning\(t\('余额不足'\)\)/)
    assert.match(page, /message\.warning\(t\('闪兑金额计算中'\)\)/)
    assert.match(page, /function getSwapErrorMessage\(error: unknown\): string/)
    assert.match(page, /async function handleSubmitSwap\(\)/)
    assert.match(page, /setSwapSubmitting\(true\)/)
    assert.match(page, /submitSwapOrder\(\{[\s\S]*amount,[\s\S]*minUsdtOut: swapMinUsdtOutAmount,[\s\S]*walletAddress: walletAddress as Address,[\s\S]*\}\)/)
    assert.match(page, /await waitForDappContractDataSync\(\)/)
    assert.match(page, /setPlatformTokenBalanceRefreshVersion\(\(current\) => current \+ 1\)/)
    assert.match(page, /setSwapRecordPageNo\(1\)/)
    assert.match(page, /setSwapRecordRefreshVersion\(\(current\) => current \+ 1\)/)
    assert.match(page, /message\.success\(t\('操作成功'\)\)/)
    assert.match(page, /setSwapSubmitting\(false\)/)
    assert.match(page, /function handleUseAllBalance\(\)/)
    assert.match(page, /setSwapAmount\(platformTokenBalanceValue\)/)
    assert.doesNotMatch(page, /function handleSwapDirection\(\)/)
    assert.match(page, /<section className="swap-page"/)
    assert.match(page, /<ContractLoading show=\{swapSubmitting\} \/>/)
    assert.match(page, /<img src=\{bg\} className="swap-page__bg"/)
    assert.match(page, /t\('Swap assets'\)/)
    assert.match(page, /t\('从'\)/)
    assert.match(page, /t\('到'\)/)
    assert.match(page, /<img src=\{walletIcon\} className="img-24 mr-8"/)
    assert.doesNotMatch(page, /52,42/)
    assert.doesNotMatch(page, /SWAP_AVAILABLE_BALANCE/)
    assert.match(page, /\{platformTokenBalanceText\}/)
    assert.match(page, /t\('全部'\)/)
    assert.match(page, /<input[\s\S]*className="[^"]*swap-page__amount-input[^"]*"[\s\S]*value=\{swapAmount\}[\s\S]*onChange=\{\(event\) => setSwapAmount\(event\.target\.value\)\}/)
    assert.match(page, /<button[\s\S]*className="[^"]*swap-page__max-button[^"]*"[\s\S]*onClick=\{handleUseAllBalance\}/)
    assert.match(page, /<div className="swap-page__switch-icon flex-center">/)
    assert.doesNotMatch(page, /className="[^"]*swap-page__switch-button[^"]*"/)
    assert.doesNotMatch(page, /onClick=\{handleSwapDirection\}/)
    assert.match(page, /<img src=\{swapIcon\} className="img-108"/)
    assert.match(page, /<div className="size-48 bold-5 tr">\{quotedUsdtText\}<\/div>/)
    assert.match(page, /<button[\s\S]*className="[^"]*swap-page__submit[^"]*"[\s\S]*onClick=\{handleSubmitSwap\}[\s\S]*disabled=\{swapSubmitting\}/)
    assert.match(page, /t\('闪兑'\)/)
    assert.match(page, /t\('闪兑记录'\)/)
    assert.doesNotMatch(page, /SWAP_RECORD_LIST\.map/)
    assert.match(page, /<InfiniteScroll[\s\S]*loading=\{swapRecordLoading\}[\s\S]*hasMore=\{swapRecordHasNextPage\}[\s\S]*onLoadMore=\{handleLoadMoreSwapRecords\}/)
    assert.match(page, /swapRecords\.length > 0 \? swapRecords\.map/)
    assert.match(page, /<Empty showGap=\{false\} className="swap-page__record-empty" \/>/)
    assert.match(page, /record\.fromAmount/)
    assert.match(page, /record\.toAmount/)
    assert.match(page, /record\.date/)
    assert.doesNotMatch(page, /手续费/)
    assert.doesNotMatch(page, /交易哈希/)
    assert.doesNotMatch(page, /record\.feeAmount/)
    assert.doesNotMatch(page, /record\.txId/)
    assert.doesNotMatch(page, /style=/)

    assert.match(styles, /\.swap-page\s*\{/)
    assert.match(styles, /background-color:\s*#001020/)
    assert.match(styles, /min-height:\s*calc\(100vh - 100px\)/)
    assert.match(styles, /min-height:\s*calc\(100dvh - 100px\)/)
    assert.match(styles, /&__bg/)
    assert.match(styles, /&__title/)
    assert.match(styles, /&__exchange-card/)
    assert.match(styles, /&__exchange-card--from/)
    assert.doesNotMatch(styles, /&__wallet-icon/)
    assert.match(styles, /&__switch-icon/)
    assert.doesNotMatch(styles, /&__switch-button/)
    assert.match(styles, /&__submit/)
    assert.match(styles, /&__submit[\s\S]*@include full-button\(/)
    assert.match(styles, /&__section-title-line/)
    assert.match(styles, /&__record-card/)
    assert.match(styles, /&__record-token-stack/)
    assert.match(styles, /&__record-line/)
})
