import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('swap page builds the static exchange screen with local interactions', async () => {
    const [page, styles] = await Promise.all([
        readFile('src/pages/main/swap/SwapPage.tsx', 'utf8'),
        readFile('src/pages/main/swap/SwapPage.scss', 'utf8'),
    ])

    assert.match(page, /import \{ useState \} from 'react'/)
    assert.match(page, /import \{ APP_CONFIG \} from '@\/config'/)
    assert.match(page, /bg from '@\/assets\/swap\/bg\.png'/)
    assert.match(page, /swapIcon from '@\/assets\/swap\/swap\.png'/)
    assert.match(page, /walletIcon from '@\/assets\/home\/wallet\.png'/)
    assert.match(page, /usdtIcon from '@\/assets\/common\/usdt\.png'/)
    assert.match(page, /const appLogoUrl = `\$\{APP_CONFIG\.routeBase\}brand\/app-logo\.png`/)
    assert.match(page, /type SwapTokenSymbol = 'Token' \| 'USDT'/)
    assert.match(page, /SWAP_TOKEN_MAP/)
    assert.match(page, /SWAP_RECORD_LIST/)
    assert.match(page, /const \[swapAmount, setSwapAmount\] = useState\(''\)/)
    assert.match(page, /const fromToken = SWAP_TOKEN_MAP\.Token/)
    assert.match(page, /const toToken = SWAP_TOKEN_MAP\.USDT/)
    assert.doesNotMatch(page, /isDirectionReversed/)
    assert.doesNotMatch(page, /setIsDirectionReversed/)
    assert.match(page, /function handleUseAllBalance\(\)/)
    assert.match(page, /setSwapAmount\(SWAP_AVAILABLE_BALANCE\)/)
    assert.doesNotMatch(page, /function handleSwapDirection\(\)/)
    assert.match(page, /<section className="swap-page"/)
    assert.match(page, /<img src=\{bg\} className="swap-page__bg"/)
    assert.match(page, /Swap assets/)
    assert.match(page, /从/)
    assert.match(page, /到/)
    assert.match(page, /<img src=\{walletIcon\} className="img-24 mr-8"/)
    assert.match(page, /52,42/)
    assert.match(page, /全部/)
    assert.match(page, /<input[\s\S]*className="[^"]*swap-page__amount-input[^"]*"[\s\S]*value=\{swapAmount\}[\s\S]*onChange=\{\(event\) => setSwapAmount\(event\.target\.value\)\}/)
    assert.match(page, /<button[\s\S]*className="[^"]*swap-page__max-button[^"]*"[\s\S]*onClick=\{handleUseAllBalance\}/)
    assert.match(page, /<div className="swap-page__switch-icon flex-center">/)
    assert.doesNotMatch(page, /className="[^"]*swap-page__switch-button[^"]*"/)
    assert.doesNotMatch(page, /onClick=\{handleSwapDirection\}/)
    assert.match(page, /<img src=\{swapIcon\} className="img-108"/)
    assert.match(page, /闪兑/)
    assert.match(page, /闪兑记录/)
    assert.match(page, /SWAP_RECORD_LIST\.map/)
    assert.match(page, /record\.fromAmount/)
    assert.match(page, /record\.toAmount/)
    assert.match(page, /record\.date/)
    assert.doesNotMatch(page, /style=/)

    assert.match(styles, /\.swap-page\s*\{/)
    assert.match(styles, /background-color:\s*#001020/)
    assert.match(styles, /min-height:\s*calc\(100vh - 100px\)/)
    assert.match(styles, /min-height:\s*calc\(100dvh - 100px\)/)
    assert.match(styles, /&__bg/)
    assert.match(styles, /&__title/)
    assert.match(styles, /&__exchange-card/)
    assert.match(styles, /&__exchange-card--from/)
    assert.doesNotMatch(styles, /&__wallet-icon/)
    assert.match(styles, /&__switch-icon/)
    assert.doesNotMatch(styles, /&__switch-button/)
    assert.match(styles, /&__submit/)
    assert.match(styles, /&__submit[\s\S]*@include full-button\(/)
    assert.match(styles, /&__section-title-line/)
    assert.match(styles, /&__record-card/)
    assert.match(styles, /&__record-token-stack/)
    assert.match(styles, /&__record-line/)
})
