import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('weight page exposes XO and weight tabs, with claim only available for XO via claimQuota', async () => {
    const [page, helper, styles, userTypes] = await Promise.all([
        readFile('src/pages/main/weight/WeightPage.tsx', 'utf8'),
        readFile('src/pages/main/weight/claim.ts', 'utf8'),
        readFile('src/pages/main/weight/WeightPage.scss', 'utf8'),
        readFile('src/features/user/types.ts', 'utf8'),
    ])

    assert.match(page, /import \{[\s\S]*useCallback,[\s\S]*useEffect,[\s\S]*useState,[\s\S]*type ChangeEvent,[\s\S]*\} from 'react'/)
    assert.match(page, /import \{ useTranslation \} from 'react-i18next'/)
    assert.match(page, /import \{ ContractLoading \} from '@\/components\/ContractLoading'/)
    assert.match(page, /import \{ Empty \} from '@\/components\/Empty'/)
    assert.match(page, /import \{ InfiniteScroll \} from '@\/components\/InfiniteScroll'/)
    assert.match(page, /import \{ message \} from '@\/components\/Message'/)
    assert.match(page, /import \{ Popup \} from '@\/components\/Popup'/)
    assert.match(page, /import \{ usePageRefresh \} from '@\/components\/PagePullRefresh'/)
    assert.match(page, /import \{ getAssetLogs \} from '@\/features\/asset\/api\.ts'/)
    assert.match(page, /import type \{ AssetLog \} from '@\/features\/asset\/types\.ts'/)
    assert.match(page, /import \{ getCurrentUser \} from '@\/features\/user\/api\.ts'/)
    assert.match(page, /import \{[\s\S]*parseDappAmountUnits,[\s\S]*waitForDappContractDataSync,[\s\S]*\} from '@\/services\/dapp'/)
    assert.match(page, /import \{ formatAmount \} from '@\/shared\/formatters\/formatAmount\.ts'/)
    assert.match(page, /import \{ useLatestRequest \} from '@\/shared\/hooks\/useLatestRequest\.ts'/)
    assert.match(page, /import bg from '@\/assets\/weight\/bg\.png'/)
    assert.match(page, /import tabActive from '@\/assets\/weight\/tab-act\.png'/)
    assert.match(page, /import tabInactive from '@\/assets\/weight\/tab\.png'/)
    assert.doesNotMatch(page, /import usdtIcon/)
    assert.doesNotMatch(page, /APP_CONFIG/)

    assert.match(page, /type WeightAssetType = 'xo' \| 'weight'/)
    assert.match(page, /type WeightBalanceField = 'balance_xo' \| 'dividend_token'/)
    assert.match(page, /type WeightAssetCurrency = WeightClaimCurrency \| 'dividend_token'/)
    assert.match(page, /const WEIGHT_ASSET_TYPE_LIST: readonly WeightAssetType\[\] = \['xo', 'weight'\]/)
    assert.match(page, /interface WeightClaimableAssetConfig extends WeightAssetConfigBase \{[\s\S]*ccy:\s*WeightClaimCurrency[\s\S]*supportsClaim:\s*true[\s\S]*\}/)
    assert.match(page, /interface WeightReadonlyAssetConfig extends WeightAssetConfigBase \{[\s\S]*ccy:\s*Exclude<WeightAssetCurrency, WeightClaimCurrency>[\s\S]*supportsClaim:\s*false[\s\S]*\}/)
    assert.match(page, /type WeightAssetConfig = WeightClaimableAssetConfig \| WeightReadonlyAssetConfig/)
    assert.match(page, /supportsAssetLogs:\s*boolean/)
    assert.match(page, /showClaimBalanceUnit:\s*boolean/)
    assert.match(page, /tabAnimationClassName:\s*string/)
    assert.match(page, /const WEIGHT_ASSET_CONFIG: Record<WeightAssetType, WeightAssetConfig> = \{[\s\S]*xo:[\s\S]*titleKey:\s*'weight\.asset\.xo'[\s\S]*symbolKey:\s*'weight\.asset\.xo'[\s\S]*tabAnimationClassName:\s*'animate__animated animate__slideInLeft'[\s\S]*ccy:\s*'balance_xo'[\s\S]*balanceField:\s*'balance_xo'[\s\S]*insufficientMessageKey:\s*'weight\.claim\.insufficientXo'[\s\S]*supportsClaim:\s*true[\s\S]*supportsAssetLogs:\s*true[\s\S]*showClaimBalanceUnit:\s*true[\s\S]*weight:[\s\S]*titleKey:\s*'weight\.asset\.weight'[\s\S]*symbolKey:\s*'weight\.asset\.weight'[\s\S]*tabAnimationClassName:\s*'animate__animated animate__slideInRight'[\s\S]*ccy:\s*'dividend_token'[\s\S]*balanceField:\s*'dividend_token'[\s\S]*insufficientMessageKey:\s*'weight\.claim\.insufficientWeight'[\s\S]*supportsClaim:\s*false[\s\S]*supportsAssetLogs:\s*false[\s\S]*showClaimBalanceUnit:\s*false/)
    assert.doesNotMatch(page, /claimType:/)
    assert.match(page, /const WEIGHT_BALANCE_EMPTY_TEXT = '--'/)
    assert.match(page, /const WEIGHT_ASSET_LOG_PAGE_SIZE = 20/)
    assert.match(page, /function createWeightAssetBalance\(value: string\): WeightAssetBalance \{[\s\S]*amount:\s*parseDappAmountUnits\(value\),[\s\S]*text:\s*formatAmount\(value\)/)
    assert.match(page, /function createEmptyWeightAssetBalances\(\): Record<WeightAssetType, WeightAssetBalance> \{[\s\S]*xo:\s*createEmptyWeightAssetBalance\(\),[\s\S]*weight:\s*createEmptyWeightAssetBalance\(\)/)

    assert.match(page, /const \[activeWeightAssetType, setActiveWeightAssetType\] = useState<WeightAssetType>\('xo'\)/)
    assert.match(page, /const \[weightBalances, setWeightBalances\] = useState\(createEmptyWeightAssetBalances\)/)
    assert.match(page, /createLatestRequestGuard: createWeightBalanceRequestGuard/)
    assert.match(page, /createLatestRequestGuard: createWeightAssetLogRequestGuard/)
    assert.match(page, /invalidateLatestRequest: invalidateWeightBalanceRequest/)
    assert.match(page, /invalidateLatestRequest: invalidateWeightAssetLogRequest/)
    assert.doesNotMatch(page, /weightBalanceRequestRef/)
    assert.doesNotMatch(page, /weightAssetLogRequestRef/)
    assert.match(page, /const activeWeightAssetConfig = WEIGHT_ASSET_CONFIG\[activeWeightAssetType\]/)
    assert.match(page, /const activeWeightAssetBalance = weightBalances\[activeWeightAssetType\]/)
    assert.match(page, /const activeWeightAssetSymbolText = t\(activeWeightAssetConfig\.symbolKey\)/)
    assert.match(page, /const refreshWeightPageData = useCallback\(async \(\) => \{[\s\S]*setWeightAssetLogPageNo\(1\)[\s\S]*const refreshTasks = \[loadWeightBalances\(\)\][\s\S]*if \(activeWeightAssetConfig\.supportsAssetLogs\) \{[\s\S]*refreshTasks\.push\(loadWeightAssetLogs\(activeWeightAssetType, 1\)\)[\s\S]*\} else \{[\s\S]*invalidateWeightAssetLogRequest\(\)[\s\S]*setWeightAssetLogs\(\[\]\)[\s\S]*setWeightAssetLogHasNextPage\(false\)[\s\S]*setWeightAssetLogLoading\(false\)[\s\S]*\}[\s\S]*await Promise\.all\(refreshTasks\)/)
    assert.match(page, /const handleWeightPullRefresh = useCallback\(\(\) => refreshWeightPageData\(\), \[refreshWeightPageData\]\)/)
    assert.match(page, /usePageRefresh\(handleWeightPullRefresh, !weightClaimSubmitting\)/)
    assert.match(page, /const loadWeightBalances = useCallback\(async \(\) => \{[\s\S]*const user = await getCurrentUser\(\)[\s\S]*setWeightBalances\(\{[\s\S]*xo:\s*createWeightAssetBalance\(user\.balance_xo\),[\s\S]*weight:\s*createWeightAssetBalance\(user\.dividend_token\),[\s\S]*\}\)/)
    assert.match(page, /setWeightBalances\(createEmptyWeightAssetBalances\(\)\)/)
    assert.match(page, /if \(!WEIGHT_ASSET_CONFIG\[assetType\]\.supportsAssetLogs\) \{[\s\S]*invalidateWeightAssetLogRequest\(\)[\s\S]*setWeightAssetLogs\(\[\]\)[\s\S]*setWeightAssetLogHasNextPage\(false\)[\s\S]*setWeightAssetLogLoading\(false\)[\s\S]*return[\s\S]*\}/)
    assert.match(page, /getAssetLogs\(\{[\s\S]*page_no: pageNo,[\s\S]*page_size: WEIGHT_ASSET_LOG_PAGE_SIZE,[\s\S]*ccy: WEIGHT_ASSET_CONFIG\[assetType\]\.ccy,[\s\S]*\}\)/)
    assert.match(page, /useEffect\(\(\) => \{[\s\S]*if \(weightAssetLogPageNo === 1\) return undefined[\s\S]*void loadWeightAssetLogs\(activeWeightAssetType, weightAssetLogPageNo\)[\s\S]*\}, \[activeWeightAssetType, loadWeightAssetLogs, weightAssetLogPageNo\]\)/)
    assert.match(page, /function handleChangeWeightAssetType\(assetType: WeightAssetType\) \{[\s\S]*if \(assetType === activeWeightAssetType\) return[\s\S]*setActiveWeightAssetType\(assetType\)[\s\S]*setWeightAssetLogPageNo\(1\)[\s\S]*if \(!WEIGHT_ASSET_CONFIG\[assetType\]\.supportsAssetLogs\) \{[\s\S]*invalidateWeightAssetLogRequest\(\)[\s\S]*\}[\s\S]*setWeightAssetLogs\(\[\]\)[\s\S]*setWeightAssetLogHasNextPage\(false\)[\s\S]*setShowWeightClaimPopup\(false\)[\s\S]*setWeightClaimAmountText\(''\)/)
    assert.match(page, /function handleOpenWeightClaimPopup\(\) \{[\s\S]*if \(!activeWeightAssetConfig\.supportsClaim\) return[\s\S]*if \(activeWeightAssetBalance\.amount <= 0n\) \{[\s\S]*message\.warning\(t\(activeWeightAssetConfig\.insufficientMessageKey\)\)[\s\S]*return[\s\S]*\}[\s\S]*setShowWeightClaimPopup\(true\)/)
    assert.match(page, /function handleUseAllWeightClaimAmount\(\) \{[\s\S]*setWeightClaimAmountText\(formatWeightClaimAllAmount\(activeWeightAssetBalance\.value\)\)/)
    assert.match(page, /function validateWeightClaimAmount\(\): string \| undefined \{[\s\S]*normalizeWeightClaimAmountInput\(weightClaimAmountText\)[\s\S]*message\.warning\(t\('请输入数量'\)\)[\s\S]*parseDappAmountUnits\(normalizedAmountText\)[\s\S]*amount > activeWeightAssetBalance\.amount[\s\S]*message\.warning\(t\('余额不足'\)\)/)
    assert.match(page, /await submitWeightClaim\(\{[\s\S]*amountText,[\s\S]*ccy:\s*activeWeightAssetConfig\.ccy,[\s\S]*\}\)/)
    assert.match(page, /await refreshWeightPageData\(\)/)
    assert.match(page, /<ContractLoading show=\{weightClaimSubmitting\} \/>/)

    assert.match(page, /<div className="weight-page__tabs flex-center gap-30">[\s\S]*WEIGHT_ASSET_TYPE_LIST\.map\(\(assetType\) => \{[\s\S]*const isActive = assetType === activeWeightAssetType[\s\S]*const tabClassName = isActive[\s\S]*\$\{config\.tabAnimationClassName\}[\s\S]*<button[\s\S]*type="button"[\s\S]*className=\{tabClassName\}[\s\S]*aria-pressed=\{isActive\}[\s\S]*onClick=\{\(\) => handleChangeWeightAssetType\(assetType\)\}[\s\S]*<img src=\{isActive \? tabActive : tabInactive\} className="weight-page__tab-bg" alt="" \/>[\s\S]*\{t\(config\.titleKey\)\}/)
    assert.match(page, /\{activeWeightAssetBalance\.text\}/)
    assert.match(page, /t\('余额'\)/)
    assert.match(page, /\{activeWeightAssetConfig\.supportsClaim \? \([\s\S]*onClick=\{handleOpenWeightClaimPopup\}[\s\S]*\) : null\}/)
    assert.doesNotMatch(page, /weight-page__token-pill/)
    assert.doesNotMatch(page, /weight-page__dividend-card/)
    assert.doesNotMatch(page, /weightDividendTokenText/)
    assert.doesNotMatch(page, /126,567\.086748/)
    assert.match(page, /\{activeWeightAssetConfig\.supportsAssetLogs \? \([\s\S]*t\('流水明细'\)[\s\S]*<InfiniteScroll[\s\S]*loading=\{weightAssetLogLoading\}[\s\S]*hasMore=\{weightAssetLogHasNextPage\}[\s\S]*onLoadMore=\{handleLoadMoreWeightAssetLogs\}[\s\S]*\) : null\}/)
    assert.match(page, /weightAssetLogs\.length > 0 \? weightAssetLogs\.map/)
    assert.match(page, /formatWeightAssetLogAmount\(record, activeWeightAssetSymbolText\)/)
    assert.match(page, /<Empty showGap=\{false\} className="pt-60 pb-60" \/>/)
    assert.match(page, /<Popup[\s\S]*show=\{showWeightClaimPopup\}[\s\S]*title=\{<span className="weight-page__claim-popup-title size-40 bold-6">\{t\('提取'\)\}<\/span>\}/)
    assert.match(page, /<label className="size-28">\{t\('提取数量'\)\}<\/label>/)
    assert.match(page, /t\('余额：'\)[\s\S]*\{activeWeightAssetBalance\.text\}[\s\S]*activeWeightAssetConfig\.showClaimBalanceUnit \? activeWeightAssetSymbolText : null/)
    assert.match(page, /placeholder=\{t\('请输入提取数量'\)\}/)
    assert.match(page, /onClick=\{handleUseAllWeightClaimAmount\}[\s\S]*>\s*\{t\('全部'\)\}\s*</)
    assert.match(page, /onClick=\{\(\) => void handleConfirmWeightClaim\(\)\}[\s\S]*disabled=\{weightClaimSubmitting\}[\s\S]*>\s*\{t\('确认'\)\}\s*</)
    assert.doesNotMatch(page, /style=/)

    assert.match(helper, /import type \{[\s\S]*Hex,[\s\S]*TransactionReceipt,[\s\S]*\} from 'viem'/)
    assert.doesNotMatch(helper, /Address/)
    assert.match(helper, /import \{ createClaim \} from '@\/features\/claim\/api\.ts'/)
    assert.match(helper, /import \{ writeLaxProjectClaimQuota \} from '@\/services\/contracts'/)
    assert.doesNotMatch(helper, /\bwriteLaxProjectClaim\b/)
    assert.doesNotMatch(helper, /WeightClaimType/)
    assert.match(helper, /export type WeightClaimCurrency = 'balance_xo'/)
    assert.match(helper, /export interface SubmitWeightClaimParams \{[\s\S]*amountText:\s*string[\s\S]*ccy:\s*WeightClaimCurrency[\s\S]*\}/)
    assert.match(helper, /export function normalizeWeightClaimAmountInput\(value: string\): string \{[\s\S]*value\.replace\(\s*\/,\/g,[\s\S]*''[\s\S]*\)\.trim\(\)/)
    assert.match(helper, /export function formatWeightClaimAllAmount\(value: string\): string \{[\s\S]*normalizeWeightClaimAmountInput\(value\)[\s\S]*fraction\.replace\(\/0\+\$\/, ''\)/)
    assert.match(helper, /export async function submitWeightClaim\([\s\S]*params: SubmitWeightClaimParams,[\s\S]*\): Promise<TransactionReceipt> \{[\s\S]*const claim = await createClaim\(\{[\s\S]*ccy:\s*params\.ccy,[\s\S]*amount:\s*params\.amountText,[\s\S]*\}\)/)
    assert.match(helper, /return writeLaxProjectClaimQuota\(\{[\s\S]*id: BigInt\(claim\.id\),[\s\S]*amount: BigInt\(claim\.amount\),[\s\S]*expiredTime: BigInt\(claim\.expire_time\),[\s\S]*signature: claim\.signature as Hex,[\s\S]*\}\)/)
    assert.doesNotMatch(helper, /claim\.token/)

    assert.match(styles, /\.weight-page\s*\{/)
    assert.match(styles, /background-color:\s*#001020/)
    assert.match(styles, /min-height:\s*calc\(100vh - 100px\)/)
    assert.match(styles, /min-height:\s*calc\(100dvh - 100px\)/)
    assert.match(styles, /&__bg/)
    assert.match(styles, /&__bg\s*\{[\s\S]*animation:\s*weight-page-bg-scale-in 0\.5s ease-out forwards/)
    assert.match(styles, /@keyframes weight-page-bg-scale-in\s*\{[\s\S]*from\s*\{[\s\S]*transform:\s*scale\(1\.2\)[\s\S]*\}[\s\S]*to\s*\{[\s\S]*transform:\s*scale\(1\)/)
    assert.match(styles, /&__tabs/)
    assert.match(styles, /&__tab\s*\{/)
    assert.match(styles, /width:\s*282px/)
    assert.match(styles, /aspect-ratio:\s*282 \/ 78/)
    assert.match(styles, /&__tab-bg/)
    assert.match(styles, /&__tab-label/)
    assert.match(styles, /&__tab--active/)
    assert.match(styles, /&__extract-button[\s\S]*@include auto-button\(/)
    assert.doesNotMatch(styles, /&__token-pill/)
    assert.doesNotMatch(styles, /&__dividend-card/)
    assert.match(styles, /&__claim-popup/)
    assert.match(styles, /&__claim-popup-title[\s\S]*@include gradient-word\(var\(--app-btn-bg\)\)/)
    assert.match(styles, /&__claim-input-wrap/)
    assert.match(styles, /&__claim-input/)
    assert.match(styles, /&__claim-all-button/)
    assert.match(styles, /&__claim-confirm[\s\S]*@include full-button\(80px,\s*999px\)/)
    assert.match(styles, /&__section-title-line/)
    assert.match(styles, /&__record-card/)
    assert.match(styles, /background:\s*linear-gradient\(135deg,\s*#1B2837 0%,\s*#0B1A29 100%\)/)
    assert.match(userTypes, /balance_xo:\s*string/)
    assert.match(userTypes, /dividend_token:\s*string/)
})
